export interface WaterPermit {
  labelFr: string
  labelEn: string
  url: string
}

export interface Water {
  id: string
  name: string
  region: string
  imageFile: string
  descFr: string
  descEn: string
  species: string[]
  bestSeason: string
  boatLaunches: string[]
  weatherRegion: string
  coords: [number, number]
  permits?: WaterPermit[]
}

export const waters: Water[] = [
  {
    id: 'fleuve-stlaurent-ouest',
    name: 'Fleuve Saint-Laurent (Ouest)',
    region: 'Montérégie / Grand Montréal',
    imageFile: 'lake-1.jpg',
    descFr: "Grand classique du sud du Québec, ce secteur du Saint-Laurent mélange herbiers, courants, battures et chenaux profonds. On y cherche surtout le maskinongé, le grand brochet, l'achigan, le doré et parfois l'esturgeon. De juin à octobre, les bordures d'herbiers et les pointes balayées par le vent donnent souvent les meilleurs poissons; en septembre et en octobre, c'est une vraie eau à trophées pour le maskinongé.",
    descEn: "A true southern Quebec classic, this stretch of the St. Lawrence mixes weed beds, current seams, flats, and deep channels. Anglers mainly target musky, northern pike, bass, walleye, and at times sturgeon. From June through October, outside weed edges and windblown points often produce best; in September and October, it becomes a legitimate trophy musky water.",
    species: ['Maskinongé', 'Grand Brochet', 'Achigan', 'Doré Jaune', 'Esturgeon'],
    bestSeason: 'Mai–Octobre',
    boatLaunches: [
      'Marina de Lachine — derrière le 3051, boul. Saint-Joseph, Lachine (Montréal), QC',
      'Rampe de LaSalle — Boul. LaSalle, Montréal',
      'Rampe de Sainte-Anne-de-Bellevue — Boul. Ste-Anne, Sainte-Anne-de-Bellevue',
    ],
    weatherRegion: 'Montréal',
    coords: [45.33, -73.78],
  },
  {
    id: 'lac-saint-pierre',
    name: 'Lac Saint-Pierre',
    region: 'Mauricie / Centre-du-Québec',
    imageFile: 'lake-2.jpg',
    descFr: "Lac mythique de la plaine du Saint-Laurent, reconnu pour ses vastes herbiers, ses chenaux et sa richesse halieutique. C'est l'une des destinations les plus sérieuses au Québec pour le maskinongé, avec d'excellentes possibilités pour le doré, le brochet, l'achigan et l'esturgeon. L'été y est productif, mais les connaisseurs attendent surtout la fin septembre et octobre, quand les gros poissons patrouillent les bordures et les cassures.",
    descEn: "A legendary lake on the St. Lawrence plain, known for its sprawling weed beds, navigation channels, and remarkable fishery. It is one of Quebec's most serious musky destinations, with strong opportunities for walleye, pike, bass, and sturgeon as well. Summer is productive, but experienced anglers especially watch late September and October, when big fish patrol edges and breaklines.",
    species: ['Maskinongé', 'Grand Brochet', 'Doré Jaune', 'Achigan', 'Esturgeon'],
    bestSeason: 'Juin–Octobre',
    boatLaunches: [
      'Rampe municipale de Saint-Ignace-de-Loyola — 2311, rang St-Pierre, Saint-Ignace-de-Loyola, QC J0K 2P0',
      'Rampe de Sorel-Tracy — Quai du Roi, Sorel-Tracy',
    ],
    weatherRegion: 'Trois-Rivières',
    coords: [46.2, -72.85],
    permits: [
      {
        labelFr: '🎫 Permis de pêche sportive du Québec (requis)',
        labelEn: '🎫 Quebec Sport Fishing Permit (required)',
        url: 'https://mondossierchassepeche.gouv.qc.ca/'
      },
      {
        labelFr: '🏞️ Autorisation spéciale Lac Saint-Pierre (réserve UNESCO)',
        labelEn: '🏞️ Special Lac Saint-Pierre Authorization (UNESCO reserve)',
        url: 'https://afclacst-pierre.org/autorisation-permis-peche/'
      }
    ],
  },
  {
    id: 'riviere-outaouais',
    name: 'Rivière Outaouais',
    region: 'Outaouais / Laurentides',
    imageFile: 'lake-3.jpg',
    descFr: "La rivière des gros espaces: longues dérives, hauts-fonds rocheux, herbiers et fosses puissantes. L'Outaouais est réputée pour son maskinongé, son doré, son brochet et son achigan, avec de très beaux secteurs du printemps tardif jusqu'à l'automne. En juin et juillet, les bordures peu profondes et les baies réchauffées sont payantes; en automne, les pointes rocheuses et les cassures du courant deviennent prioritaires.",
    descEn: "A river of big water: long drifts, rocky shoals, weed beds, and powerful holes. The Ottawa River is respected for musky, walleye, pike, and bass, with excellent zones from late spring into fall. In June and July, shallow warming bays and edges are productive; in fall, rocky points and current breaklines become prime areas.",
    species: ['Maskinongé', 'Grand Brochet', 'Achigan', 'Doré Jaune'],
    bestSeason: 'Mai–Novembre',
    boatLaunches: [
      'Port de plaisance de Gatineau — 1, rue Jacques-Cartier, Gatineau, QC J8X 3P9',
      'Rampe de Grenville — Rue du Quai, Grenville',
      'Rampe de Rigaud — Ch. du Bord-de-l\'Eau, Rigaud',
    ],
    weatherRegion: 'Gatineau',
    coords: [45.8, -74.6],
  },
  {
    id: 'lac-deux-montagnes',
    name: 'Lac des Deux Montagnes',
    region: 'Laurentides / Montérégie',
    imageFile: 'lake-4.jpg',
    descFr: "Plan d'eau culte pour les amateurs de maskinongé près de Montréal, le lac des Deux Montagnes combine eau teintée, herbiers clairsemés, pointes et chenaux. On y pêche surtout le maskinongé, le brochet, le doré et l'achigan. Le début d'été peut être très bon, mais la réputation du lac se joue surtout en septembre et en octobre, quand les poissons trophées suivent les bordures externes et les structures battues par le vent.",
    descEn: "A legendary musky water close to Montreal, Lake of Two Mountains combines stained water, sparse weeds, points, and channels. Anglers mainly pursue musky, pike, walleye, and bass here. Early summer can be solid, but the lake's real reputation comes in September and October, when trophy fish follow outside edges and wind-blown structure.",
    species: ['Maskinongé', 'Grand Brochet', 'Achigan', 'Doré Jaune'],
    bestSeason: 'Juin–Octobre',
    boatLaunches: [
      'Rampes municipales de Deux-Montagnes (réservées aux résidents, vignette requise) — Deux-Montagnes, QC',
      'Parc Gagné — 270, boulevard des Prairies, Laval, QC H7N 2T9 (accès public, côté rivière des Prairies)',
    ],
    weatherRegion: 'Laval',
    coords: [45.45, -74.0],
  },
  {
    id: 'reservoir-gouin',
    name: 'Réservoir Gouin',
    region: 'Haute-Mauricie',
    imageFile: 'lake-5.jpg',
    descFr: "Immense territoire de pourvoiries, d'îles, de baies et de bois noyé, le réservoir Gouin est une destination nordique de référence. Le doré jaune et le grand brochet y dominent, avec du touladi dans certains secteurs profonds et de l'omble de fontaine dans des eaux plus fraîches. De juin à septembre, la pêche est forte; en début d'été, les baies sombres et les structures de bois sont excellentes, tandis qu'en fin de saison les cassures et les pointes plus profondes prennent le relais.",
    descEn: "A vast northern maze of outfitter territory, islands, bays, and flooded timber, the Gouin Reservoir is a benchmark destination in Quebec. Walleye and northern pike are the main draws, with lake trout in certain deep sectors and brook trout in cooler connected waters. From June to September it fishes well; early summer shines in dark bays and timber, while late season shifts attention to deeper breaks and points.",
    species: ['Grand Brochet', 'Doré Jaune', 'Truite Mouchetée', 'Touladi'],
    bestSeason: 'Juin–Septembre',
    boatLaunches: [
      'Pourvoirie Barrage Gouin et Magnan — 431, Réservoir Gouin, La Tuque, QC',
      'Accès route forestière — coordonnées GPS: 48.35, -74.98',
    ],
    weatherRegion: 'La Tuque',
    coords: [48.55, -74.8],
  },
  {
    id: 'lac-saint-jean',
    name: 'Lac Saint-Jean',
    region: 'Saguenay–Lac-Saint-Jean',
    imageFile: 'lake-6.jpg',
    descFr: "Grand lac ouvert, venteux et spectaculaire, le lac Saint-Jean est surtout associé à la ouananiche, mais il offre aussi du doré, du brochet et de l'omble de fontaine selon les secteurs. Les entrées de rivière, les pointes balayées par le vent et certaines battures font partie des zones clés. De juin à septembre, la fenêtre est la meilleure, avec des matinées et soirées particulièrement fortes quand le lac est mobile mais pêchable.",
    descEn: "A huge open, windswept, dramatic lake, Lac Saint-Jean is best known for landlocked salmon, but it also offers walleye, pike, and brook trout depending on the area. River mouths, windblown points, and selected flats are key zones. June through September is the prime window, with dawn and evening often strongest when the lake has movement but remains fishable.",
    species: ['Doré Jaune', 'Grand Brochet', 'Ouananiche', 'Truite Mouchetée'],
    bestSeason: 'Juin–Septembre',
    boatLaunches: [
      'Marina de Roberval — 854, rue Arthur, Roberval, QC G8H 2M7',
      'Marina d\'Alma — Rue du Pont, Alma',
      'Rampe de Dolbeau-Mistassini — Boul. des Pionniers, Dolbeau-Mistassini',
    ],
    weatherRegion: 'Saguenay',
    coords: [48.6, -72.0],
  },
  {
    id: 'lac-memphremagog',
    name: 'Lac Memphrémagog',
    region: 'Estrie',
    imageFile: 'lake-7.jpg',
    descFr: "Lac profond de l'Estrie aux eaux plus claires, Memphrémagog demande une approche plus fine que plusieurs grands plans d'eau du sud. On y trouve achigan, brochet, doré et truite arc-en-ciel, avec des secteurs rocheux, des tombants marqués et des anses plus calmes. Le printemps tardif et le début d'automne sont souvent excellents, surtout pour l'achigan et le brochet actifs sur les transitions roche-herbier.",
    descEn: "A deep Eastern Townships lake with clearer water, Memphrémagog often requires a more refined approach than many large southern waters. It holds bass, pike, walleye, and rainbow trout, with rocky structure, sharp drop-offs, and calmer coves. Late spring and early fall are often outstanding, especially for bass and pike working rock-to-weed transitions.",
    species: ['Grand Brochet', 'Achigan', 'Doré Jaune', 'Truite Arc-en-ciel'],
    bestSeason: 'Mai–Octobre',
    boatLaunches: [
      'Capitainerie / rampe de mise à l\'eau — 353, rue de Hatley, Magog, QC J1X 3N2',
      'Rampe de Bolton-Est — Ch. Missisquoi, Bolton-Est',
      'Newport Public Boat Launch — Newport, VT (côté américain)',
    ],
    weatherRegion: 'Sherbrooke',
    coords: [45.1, -72.25],
  },
  {
    id: 'lac-champlain',
    name: 'Lac Champlain',
    region: 'Montérégie / Vermont',
    imageFile: 'lake-8.jpg',
    descFr: "Référence nord-américaine pour les gros poissons, le lac Champlain est vaste, varié et très vivant. Côté québécois comme dans l'ensemble du bassin, on y cherche surtout le brochet, l'achigan, le doré et le maskinongé. Les baies réchauffées du début de saison sont excellentes, puis l'été et le début d'automne favorisent les herbiers denses, les quais, les plateaux rocheux et les cassures plus profondes.",
    descEn: "A North American reference water for big fish, Lake Champlain is broad, varied, and highly productive. On the Quebec side and across the basin, anglers mainly target pike, bass, walleye, and musky. Warm early-season bays can be excellent, then summer and early fall favor dense weeds, docks, rocky flats, and deeper breaks.",
    species: ['Grand Brochet', 'Achigan', 'Doré Jaune', 'Maskinongé'],
    bestSeason: 'Mai–Octobre',
    boatLaunches: [
      'Marina Le Sieur de Champlain — 195, rang de la Barbotte, Lacolle, QC J0J 1J0',
      'Rouses Point Public Ramp — Rouses Point, NY (côté américain)',
    ],
    weatherRegion: 'Saint-Jean-sur-Richelieu',
    coords: [45.05, -73.15],
  },
  {
    id: 'riviere-richelieu',
    name: 'Rivière Richelieu',
    region: 'Montérégie',
    imageFile: 'lake-9.jpg',
    descFr: "Rivière emblématique de la Montérégie, la Richelieu offre une pêche accessible mais jamais banale. Ses herbiers, quais, fosses et bordures de courant tiennent du brochet, de l'achigan, du doré et de l'esturgeon selon les secteurs. Du printemps à l'automne, elle récompense les pêcheurs précis; les périodes de faible lumière et les changements de débit y déplacent souvent les bancs de poissons actifs.",
    descEn: "An iconic Montérégie river, the Richelieu offers accessible fishing that is never ordinary. Its weeds, docks, holes, and current edges hold pike, bass, walleye, and sturgeon depending on the area. From spring through fall it rewards precision, and low-light periods plus flow changes often reposition active fish.",
    species: ['Grand Brochet', 'Achigan', 'Doré Jaune', 'Esturgeon'],
    bestSeason: 'Avril–Octobre',
    boatLaunches: [
      'Débarcadère municipal — 405, chemin des Patriotes, Saint-Charles-sur-Richelieu, QC J0H 2G0',
      'Rampe de Saint-Jean-sur-Richelieu — Boul. du Séminaire, Saint-Jean-sur-Richelieu',
      'Rampe de Sorel — Rue du Roi, Sorel-Tracy',
    ],
    weatherRegion: 'Longueuil',
    coords: [45.35, -73.25],
  },
  {
    id: 'fleuve-stlaurent-est',
    name: 'Fleuve Saint-Laurent (Est)',
    region: 'Bas-Saint-Laurent / Gaspésie',
    imageFile: 'lake-10.jpg',
    descFr: "Ici, le fleuve change de visage: eau plus froide, influence maritime, grands courants et secteurs côtiers puissants. On y pense d'abord au bar rayé là où il est présent, mais aussi à l'esturgeon et, selon les zones, à quelques secteurs de brochet ou de doré. La meilleure période va surtout de juin à septembre, quand les marées, les vents et les mouvements de nourriture dictent vraiment l'action.",
    descEn: "Here the St. Lawrence changes character: colder water, stronger tidal influence, and powerful coastal currents. Where present, striped bass is the headline species, with sturgeon and, in certain areas, some pike or walleye opportunities as well. The best window is mainly June through September, when tides, wind, and bait movement truly dictate the action.",
    species: ['Bar Rayé', 'Esturgeon', 'Grand Brochet', 'Doré Jaune'],
    bestSeason: 'Juin–Septembre',
    boatLaunches: [
      'Rampe de Rimouski — Rue Saint-Germain, Rimouski',
      'Rampe de Rivière-du-Loup — Rue Fraser, Rivière-du-Loup',
      'Rampe de Matane — Quai de Matane, Matane',
    ],
    weatherRegion: 'Rimouski',
    coords: [48.5, -68.5],
  },
  {
    id: 'riviere-gatineau',
    name: 'Rivière Gatineau',
    region: 'Outaouais',
    imageFile: 'lake-11.jpg',
    descFr: "La Gatineau offre un mélange intéressant de rivière habitée et de secteurs plus sauvages en remontant vers le nord. On y pêche surtout le brochet, le doré et l'achigan, avec de l'omble de fontaine dans certaines portions plus fraîches ou tributaires. La fin du printemps et l'été y sont productifs, surtout autour des embouchures, des cassures et des secteurs où le courant ralentit juste assez pour concentrer les poissons.",
    descEn: "The Gatineau River offers a compelling mix of settled water and wilder northern stretches. Anglers mainly target pike, walleye, and bass, with brook trout in certain cooler sections or tributaries. Late spring and summer are productive, especially around mouths, breaks, and current zones that slow just enough to concentrate fish.",
    species: ['Grand Brochet', 'Doré Jaune', 'Achigan', 'Truite Mouchetée'],
    bestSeason: 'Mai–Septembre',
    boatLaunches: [
      'Rampe de Maniwaki — Rue du Pont, Maniwaki',
      'Rampe de Gracefield — Ch. du Lac-Gault, Gracefield',
      'Accès de Gatineau — Boul. de la Gappe, Gatineau',
    ],
    weatherRegion: 'Gatineau',
    coords: [46.5, -75.5],
  },
  {
    id: 'riviere-saint-maurice',
    name: 'Rivière Saint-Maurice',
    region: 'Mauricie',
    imageFile: 'lake-12.jpg',
    descFr: "Grande rivière mauricienne, la Saint-Maurice alterne rapides, fosses, barrages, bordures calmes et longs corridors de déplacement. Le doré y est une espèce phare, accompagné du brochet, du maskinongé dans certains tronçons et de la truite mouchetée plus en amont. De mai à octobre, elle peut être excellente, avec des poissons souvent calés sur les premières cassures à l'extérieur du plus gros courant.",
    descEn: "A major Mauricie river, the Saint-Maurice alternates rapids, holes, dams, calm edges, and long travel corridors. Walleye is a signature species here, joined by pike, musky in certain stretches, and brook trout farther upstream. From May through October it can fish very well, with many fish set on the first breaks just outside the main current.",
    species: ['Doré Jaune', 'Grand Brochet', 'Truite Mouchetée', 'Maskinongé'],
    bestSeason: 'Mai–Octobre',
    boatLaunches: [
      'Rampe de Shawinigan — Rue Commerciale, Shawinigan',
      'Rampe de Grand-Mère — Rue de la Rivière, Grand-Mère',
      'Rampe de La Tuque — Rue Saint-Antoine, La Tuque',
    ],
    weatherRegion: 'Trois-Rivières',
    coords: [47.5, -73.5],
  },
  {
    id: 'lac-temiscamingue',
    name: 'Lac Témiscamingue',
    region: 'Abitibi-Témiscamingue',
    imageFile: 'lake-13.jpg',
    descFr: "Long lac-rivière frontalier, profond par endroits et balayé par le vent, le Témiscamingue a tout d'une grande eau de caractère. On y vise le doré, le brochet, le maskinongé et, dans certaines zones, l'omble de fontaine. L'été donne de belles pêches, mais le début d'automne est particulièrement intéressant pour les gros prédateurs qui montent sur les pointes, les plateaux et les cassures exposées.",
    descEn: "A long border lake-river, deep in places and shaped by wind, Lake Témiscamingue has all the character of serious big water. Anglers target walleye, pike, musky, and in some areas brook trout. Summer can be very good, but early fall is especially interesting for large predators moving onto points, flats, and exposed breaklines.",
    species: ['Grand Brochet', 'Doré Jaune', 'Maskinongé', 'Truite Mouchetée'],
    bestSeason: 'Juin–Septembre',
    boatLaunches: [
      'Rampe de Ville-Marie — Rue Notre-Dame-de-Lourdes, Ville-Marie',
      'Rampe de Témiscaming — Rue Kipawa, Témiscaming (ON)',
      'Accès de Guigues — Route du Lac-Témiscamingue, Guigues',
    ],
    weatherRegion: 'Rouyn-Noranda',
    coords: [47.2, -79.5],
  },
  {
    id: 'lac-abitibi',
    name: 'Lac Abitibi',
    region: 'Abitibi-Témiscamingue',
    imageFile: 'lake-14.jpg',
    descFr: "Vaste lac du nord-ouest québécois, le lac Abitibi offre une pêche franche, sauvage et souvent très régulière. Le brochet, le doré et la perchaude y dominent, avec de nombreux secteurs de baies, de roches et de plateaux peu profonds. La meilleure saison va de juin à août; les périodes de vent modéré et de lumière basse y relancent souvent l'activité des prédateurs et des bancs de perchaude.",
    descEn: "A broad lake in Quebec's northwest, Lake Abitibi offers straightforward, wild, often very consistent fishing. Pike, walleye, and yellow perch dominate, with plenty of bays, rock, and shallow flats to work. The prime season runs from June to August, and moderate wind plus low light often re-ignite predator activity and perch schools.",
    species: ['Grand Brochet', 'Doré Jaune', 'Perchaude'],
    bestSeason: 'Juin–Août',
    boatLaunches: [
      'Rampe de La Sarre — Rue Principale, La Sarre',
      'Accès de Palmarolle — Route de l\'Abitibi, Palmarolle',
      'Rampe de Dupuy — Ch. du Lac-Abitibi, Dupuy',
    ],
    weatherRegion: 'Amos',
    coords: [48.7, -79.2],
  },
  {
    id: 'lac-massawippi',
    name: 'Lac Massawippi',
    region: 'Estrie',
    imageFile: 'lake-15.jpg',
    descFr: "Lac élégant de l'Estrie, profond et relativement clair, Massawippi est surtout intéressant pour l'achigan, le brochet et la truite arc-en-ciel. Ses tombants, quais, pointes et rives rocheuses demandent de la précision et une présentation propre. L'été stable peut être très bon tôt et tard dans la journée, alors que le début de l'automne favorise souvent les poissons plus actifs sur les bordures.",
    descEn: "An elegant Eastern Townships lake, deep and relatively clear, Massawippi is mainly known for bass, pike, and rainbow trout. Its drop-offs, docks, points, and rocky shoreline demand precision and clean presentations. Stable summer weather can be very good early and late in the day, while early fall often brings more active fish to the edges.",
    species: ['Achigan', 'Grand Brochet', 'Truite Arc-en-ciel'],
    bestSeason: 'Juin–Septembre',
    boatLaunches: [
      "Rampe de North Hatley — Rue Massawippi, North Hatley",
      "Rampe d'Ayer's Cliff — Rue du Lac, Ayer's Cliff",
    ],
    weatherRegion: 'Sherbrooke',
    coords: [45.05, -71.95],
  },
  {
    id: 'fleuve-stlaurent-central',
    name: 'Fleuve Saint-Laurent (Central)',
    region: 'Centre-du-Québec / Chaudière-Appalaches',
    imageFile: 'lake-16.jpg',
    descFr: "Dans ce secteur central du fleuve, les grands chenaux rencontrent battures, pointes, fosses et bordures très productives. On y trouve maskinongé, doré, esturgeon et brochet, avec une vraie ambiance de grand fleuve québécois. L'été donne de belles possibilités, mais septembre-octobre se distingue pour les gros poissons, surtout là où le vent, le courant et la structure se croisent.",
    descEn: "In this central reach of the river, major channels meet flats, points, holes, and highly productive edges. Musky, walleye, sturgeon, and pike are all present, giving it the full feel of big-river Quebec fishing. Summer offers strong opportunity, but September and October stand out for larger fish, especially where wind, current, and structure intersect.",
    species: ['Maskinongé', 'Doré Jaune', 'Esturgeon', 'Grand Brochet'],
    bestSeason: 'Juin–Octobre',
    boatLaunches: [
      'Rampe de Bécancour — Boul. des Acadiens, Bécancour',
      'Rampe de Lévis — Rue du Fleuve, Lévis',
      'Rampe de Saint-Nicolas — Ch. de la Pointe, Saint-Nicolas',
    ],
    weatherRegion: 'Québec',
    coords: [46.4, -72.5],
  },
  {
    id: 'riviere-rouge',
    name: 'Rivière Rouge',
    region: 'Laurentides',
    imageFile: 'lake-17.jpg',
    descFr: "La Rouge alterne belles portions calmes, courants, fosses et sections plus fraîches, ce qui en fait une rivière variée à l'échelle d'une saison. On y pêche le brochet, l'achigan, le doré et parfois l'omble de fontaine selon les secteurs. Du printemps tardif à septembre, elle récompense bien la lecture du courant et des accès à l'eau plus profonde près des roches, des arbres tombés et des embouchures.",
    descEn: "The Rouge alternates calm reaches, current, holes, and cooler sections, making it a varied river across a full season. Anglers pursue pike, bass, walleye, and at times brook trout depending on the section. From late spring through September it rewards reading current and locating deeper access near rock, laydowns, and tributary mouths.",
    species: ['Grand Brochet', 'Achigan', 'Truite Mouchetée', 'Doré Jaune'],
    bestSeason: 'Mai–Septembre',
    boatLaunches: [
      'Rampe de Lachute — Rue Principale, Lachute',
      'Accès de Calumet — Route 148, Calumet',
      'Rampe de L\'Annonciation — Rue de la Rivière, L\'Annonciation',
    ],
    weatherRegion: 'Mont-Tremblant',
    coords: [46.4, -74.8],
  },
  {
    id: 'lac-des-seize-iles',
    name: 'Lac des Seize Îles',
    region: 'Laurentides',
    imageFile: 'lake-18.jpg',
    descFr: "Petit plan d'eau des Laurentides au profil plus intime, le lac des Seize Îles demande une pêche d'observation: quais, roches, herbiers épars et transitions nettes. On y cherche surtout le brochet, l'achigan et le doré. En été, les bordures ombragées et les premières cassures donnent souvent le ton; en fin de saison, les poissons se regroupent davantage sur les structures les plus marquées.",
    descEn: "A more intimate Laurentians lake, Lac des Seize Îles calls for an observant style of fishing: docks, rock, scattered weeds, and sharp transitions. Pike, bass, and walleye are the main targets. In summer, shaded edges and first breaks often set the pattern; later in the season, fish group more tightly on the strongest structure.",
    species: ['Grand Brochet', 'Achigan', 'Doré Jaune'],
    bestSeason: 'Juin–Septembre',
    boatLaunches: [
      'Accès de Sainte-Sophie — Ch. du Lac-des-Seize-Îles, Sainte-Sophie',
      'Accès de Saint-Hippolyte — Montée des Hauteurs, Saint-Hippolyte',
    ],
    weatherRegion: 'Saint-Jérôme',
    coords: [46.1, -74.7],
  },
  {
    id: 'lac-saint-francois',
    name: 'Lac Saint-François',
    region: 'Montérégie',
    imageFile: 'lake-19.jpg',
    descFr: "Grande eau frontalière du sud-ouest, le lac Saint-François est reconnu pour ses puissants prédateurs et ses secteurs balayés par le vent. Maskinongé, brochet, achigan et doré y occupent herbiers, pointes, chenaux et zones de transition. De juin à octobre, le lac peut être excellent; les journées avec un bon vent de travers activent souvent les poissons sur les bordures externes et les structures ouvertes.",
    descEn: "A major border water in the southwest, Lac Saint-François is known for strong predators and wind-driven structure. Musky, pike, bass, and walleye use its weeds, points, channels, and transition zones. From June through October it can be excellent, and days with good crosswind often activate fish along outside edges and open structure.",
    species: ['Maskinongé', 'Grand Brochet', 'Achigan', 'Doré Jaune'],
    bestSeason: 'Juin–Octobre',
    boatLaunches: [
      'Rampe de Salaberry-de-Valleyfield — Boul. du Havre, Salaberry-de-Valleyfield',
      'Rampe de Dundee — Route 132, Dundee',
      'Accès d\'Akwesasne — Route 132, Saint-Régis',
    ],
    weatherRegion: 'Salaberry-de-Valleyfield',
    coords: [45.15, -74.5],
  },
  {
    id: 'riviere-madeleine',
    name: 'Rivière Madeleine',
    region: 'Gaspésie',
    imageFile: 'lake-20.jpg',
    descFr: "Rivière gaspésienne au caractère nettement salmonicole, la Madeleine évoque d'abord le saumon atlantique, mais aussi l'omble de fontaine et parfois la truite arc-en-ciel selon les secteurs. L'eau fraîche, les fosses bien marquées et les veines de courant propres font sa réputation. De juin à septembre, elle exige discrétion, lecture fine et respect absolu des règlements locaux propres aux rivières à saumon du Québec.",
    descEn: "A Gaspésie river with a strongly salmon-focused identity, the Madeleine is first and foremost associated with Atlantic salmon, along with brook trout and, in some sectors, rainbow trout. Cold water, defined holding pools, and clean current lanes make its reputation. From June through September it demands stealth, refined reading of water, and full respect for local regulations specific to Quebec salmon rivers.",
    species: ['Truite Mouchetée', 'Saumon Atlantique', 'Truite Arc-en-ciel'],
    bestSeason: 'Juin–Septembre',
    boatLaunches: [
      'Accès de Madeleine-Centre — Route 132, Madeleine-Centre',
      'Rampe de Cap-Chat — Rue du Quai, Cap-Chat',
    ],
    weatherRegion: 'Gaspé',
    coords: [48.9, -65.5],
  },
]
